server:
  port: 8081

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:h2:mem:userdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

  graphql:
    graphiql:
      enabled: true

  rabbitmq:
    host: localhost
    port: 5672
    username: myservice
    password: myservice1234